CREATE TABLE hw_item_graphics_card(
  id INTEGER PRIMARY KEY NOT NULL,
  gc_interface VARCHAR (40),
  gc_max_resolution VARCHAR (40),
  gc_model VARCHAR (255),
  gc_cooling VARCHAR (255),
  gc_recommended_for_gaming SMALLINT,
  gc_chipset_producer VARCHAR (255),
  gc_series VARCHAR (255),
  gc_nanometers VARCHAR (40),
  gc_graphics_processor VARCHAR (255),
  gc_release_date DATE,
  gc_pixel_shader_version VARCHAR (255),
  gc_vertex_shader_version VARCHAR (255),
  gc_pixel_fill_rate VARCHAR (255),
  gc_texture_fill_rate VARCHAR (255),
  gc_texture_units SMALLINT,
  gc_raster_operators SMALLINT,
  gc_transistors_number SMALLINT,
  gc_cuda_cores SMALLINT,
  gc_oc_maximum_bandwith VARCHAR (255),
  gc_directx_support VARCHAR (255),
  gc_opengl_support VARCHAR (255),
  gc_vulkan_support BOOLEAN,
  gc_gsync_support BOOLEAN,
  gc_vr_ready_support BOOLEAN,
  gc_hdmi_ports SMALLINT,
  gc_display_ports SMALLINT,
  gc_hdtv_support BOOLEAN,
  created_on TIMESTAMPTZ,
  updated_on TIMESTAMPTZ,
  hardware_item_id INTEGER,
  CONSTRAINT fk_hardware_item_graphics_card FOREIGN KEY (hardware_item_id)
  REFERENCES gamers_market.hw_item(id),
  UNIQUE (id)
);